// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Model.Models;

public partial class BearManagementContext : DbContext
{
    public BearManagementContext()
    {
    }

    public BearManagementContext(DbContextOptions<BearManagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BearAccount> BearAccounts { get; set; }

    public virtual DbSet<BearProfile> BearProfiles { get; set; }

    public virtual DbSet<BearType> BearTypes { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BearAccount>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK__BearAcco__349DA58688423B24");

            entity.ToTable("BearAccount");

            entity.HasIndex(e => e.RoleId, "IX_BearAccount_RoleId");

            entity.HasIndex(e => e.UserName, "IX_BearAccount_UserName");

            entity.HasIndex(e => e.UserName, "UQ__BearAcco__C9F2845637591F0C").IsUnique();

            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(20);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<BearProfile>(entity =>
        {
            entity.HasKey(e => e.BearProfileId).HasName("PK__BearProf__17E64CD7F240BD23");

            entity.ToTable("BearProfile");

            entity.HasIndex(e => e.BearTypeId, "IX_BearProfile_BearTypeId");

            entity.Property(e => e.BearName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.BearWeight).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ModifiedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.BearType).WithMany(p => p.BearProfiles)
                .HasForeignKey(d => d.BearTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BearProfile_BearType");
        });

        modelBuilder.Entity<BearType>(entity =>
        {
            entity.HasKey(e => e.BearTypeId).HasName("PK__BearType__ECEEBC1476B44DE5");

            entity.ToTable("BearType");

            entity.Property(e => e.BearTypeName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Origin).HasMaxLength(200);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}